// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlruh6Y26k6IyKgJY3Uew1iEwzVfnTaeA',
    appId: '1:872354225333:web:fe7b1950b5e8e1cc3b72fc',
    messagingSenderId: '872354225333',
    projectId: 'todozen-dbb21',
    authDomain: 'todozen-dbb21.firebaseapp.com',
    storageBucket: 'todozen-dbb21.firebasestorage.app',
    measurementId: 'G-ES477BBPM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfUYFgOklbGcR2cfSs64d2FK50qI_vBZc',
    appId: '1:872354225333:android:9bf71c3c99ce242a3b72fc',
    messagingSenderId: '872354225333',
    projectId: 'todozen-dbb21',
    storageBucket: 'todozen-dbb21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8TaU4e1EUPEFerk5J1xEkAVlJ9sc95pc',
    appId: '1:872354225333:ios:84d6a7e6c69b74703b72fc',
    messagingSenderId: '872354225333',
    projectId: 'todozen-dbb21',
    storageBucket: 'todozen-dbb21.firebasestorage.app',
    iosBundleId: 'com.example.todoZen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8TaU4e1EUPEFerk5J1xEkAVlJ9sc95pc',
    appId: '1:872354225333:ios:84d6a7e6c69b74703b72fc',
    messagingSenderId: '872354225333',
    projectId: 'todozen-dbb21',
    storageBucket: 'todozen-dbb21.firebasestorage.app',
    iosBundleId: 'com.example.todoZen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlruh6Y26k6IyKgJY3Uew1iEwzVfnTaeA',
    appId: '1:872354225333:web:20025f1a90f620e33b72fc',
    messagingSenderId: '872354225333',
    projectId: 'todozen-dbb21',
    authDomain: 'todozen-dbb21.firebaseapp.com',
    storageBucket: 'todozen-dbb21.firebasestorage.app',
    measurementId: 'G-MEB7W2BHJZ',
  );

}